import { AppHeader } from '@/components/header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootLayoutComponent>{children}</RootLayoutComponent>
      </body>
    </html>
  )
}

export const RootLayoutComponent = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <>
      <AppHeader />
      <div className="container mx-auto px-4 ">
        {children}
      </div>
      <Toaster />
    </>
  )
}